jobs:
  culture-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "\u8BBE\u7F6EPython"
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: "\u5B89\u88C5\u4F9D\u8D56"
      run: pip install -r requirements.txt
    - name: "\u6267\u884C\u6587\u5316\u68C0\u67E5"
      run: "PYTHONPATH=. python -c \"from aiculture.culture_enforcer import CultureEnforcer;\
        \ result = CultureEnforcer('.').enforce_all(); print(f'\u8D28\u91CF\u8BC4\u5206\
        : {result[\\\"score\\\"]}/100'); exit(1 if result['errors'] > 0 else 0)\""
    - name: "\u8FD0\u884C\u6D4B\u8BD5"
      run: python -m pytest --cov=aiculture --cov-report=xml
    - name: "\u4E0A\u4F20\u8986\u76D6\u7387\u62A5\u544A"
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
name: "\u6587\u5316\u68C0\u67E5"
'on':
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop
